# Generated by Django 3.1.4 on 2021-01-21 16:26

import awesome_avatar.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', awesome_avatar.fields.AvatarField(upload_to='avatars', verbose_name='Avarta')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True, verbose_name='University')),
                ('primary_school', models.TextField(blank=True, null=True, verbose_name='Primary School')),
                ('high_school', models.TextField(blank=True, null=True, verbose_name='High School')),
                ('city', models.TextField(blank=True, null=True, verbose_name='City')),
                ('state', models.TextField(blank=True, null=True, verbose_name='State/Province')),
                ('zip', models.TextField(blank=True, null=True, verbose_name='Zip Code')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Country')),
                ('like', models.IntegerField(default=0, verbose_name='Like')),
                ('dislike', models.IntegerField(default=0, verbose_name='Dis Like')),
                ('rank', models.FloatField(default=0.0, verbose_name='Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
    ]
